FROM node:24-alpine AS development

WORKDIR /usr/src/app

# Install openssl for Prisma
RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm ci

COPY . .
RUN if [ -f prisma/schema.prisma ]; then npx prisma generate; fi

CMD ["npm", "run", "dev"]
